@url_dev=http://localhost:3091/v1/api

## signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: acccccc

{
    "name": "Shop K2",
    "email": "k21222@gmail.com",
    "password": "Abc@1234"
}